name: Chrome
on: push
env:
  CYPRESS_username: ${{secrets.CYPRESS_USERNAME}}
  CYPRESS_password: ${{secrets.CYPRESS_PASSWORD}}
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
